apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: compilador
  description: Compilador para a matéria de compiladores
  labels:
    example.com/custom: custom_label_value
  annotations:
    example.com/service-discovery: compilador
    circleci.com/project-slug: github/example-org/artist-website
  tags:
    - python
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: website
  lifecycle: production
  owner: artist-relations-team
  system: public-websites